### ISSUE TITLE
ROADMAP 1.0 Release

### ISSUE THREAD

**Issue by fosslinux** [fosslinux/live-bootstrap#292]
We are now in a place where a 1.0 release is in the near future. The primary goal for the 1.0 release is:

To provide a complete end-to-end software bootstrap from hex0 + kaem-minimal + builder-hex0 to a modern Linux toolchain and associated utilities; for the X86 (32-bit) architecture that works on i686 processors; that is comprehensible and documented sufficiently by someone who does not know bootstrapping; and has a reasonably logical UX.

Roadmap:

- [ ] 1.0 branch: when 1.0 is branched, no changes that don't clearly add to this above goal will not be added to that branch.
- [ ] detailed testing: test on as wide of a variety of systems as possible.
- [ ] 1.0 RC: final changes and signifying release
- [ ] 1.0 Release: last RC that has no changes required becomes release

goal is to have 1.0 out by early July (if it's done earlier, great!)

Changes before 1.0:

- [ ] Kernel stuff: 1.0 will be using Fiwix in some fashion.
  - [ ] Either kexec Fiwix -> Linux support, or reboot support. (@rick-masters, do you think Fiwix -> Linux support will be ready for 1.0, or shall we go with a reboot for 1.0?)
  - [ ] Running sysa on a disk. (@rick-masters are there any blockers within Fiwix to an impl of this on the live-bootstrap side? If yes, is this achievable for 1.0?)
- [ ] General updates
  - I don't wish to go too crazy with this - just toolchain stuff mainly.
  - [ ] GCC 13 (nearly done)
  - [ ] Binutils 2.40
  - [ ] musl 1.2.4
  - [ ] no pre-musl binaries in final system
    - [ ] tar
    - [ ] gzip
- [ ] Docs (@fosslinux)
  - [ ] Ensure `parts.rst` accurately reflects current state (will be done post all other package changes)
  - [ ] Update `README.md` to reflect initial goal completion and current state of project
  - [ ] Provide more detailed instructions on how to prepare and run the project, most notably without `rootfs.py`
  - [ ] Describe how to "latch on" to the end of live-bootstrap (eg, freedesktop-sdk)
- [ ] UX (@fosslinux)
  - [ ] Make as many options as possible tunable from within live-bootstrap if not set in `bootstrap.cfg`
    - [ ] particularly, disk selection
  - [ ] Provide option for not all command output to be displayed on-screen
- ??

Things that are explicitly out of scope:

- any kind of architectural expansion
- solving the "how to get initial files onto a disk" problem
- support for any less than 4GB of RAM
- bootloader

Anything else to add to above please comment.

**Comment by stikonas** [comment]
>       * [ ]  Running sysa on a disk. (@rick-masters are there any blockers within Fiwix to an impl of this on the live-

Hmm, I'm not fully convinced that we should add sysa on disk as a hard requirement... Right now I think we have an interesting use-case of preparing builder-hex0 bootable image on portable USB stick and using it as "installer".

If we add this requirement, then it won't be possible to run live-bootstrap on a laptop with just NVMe drive.

**Comment by fosslinux** [comment]
Hmm, ok that is a compelling point. I agree at least for that case. Let's drop on-disk sysa for 1.0.

**Comment by stikonas** [comment]
@fosslinux Hmm, in addition to toolchain updates, it might also make sense to update crypto packages, in particular nss (I think we use it for certificate bundle) and if possible OpenSSL 3.

**Comment by fosslinux** [comment]
If OpenSSL 3 is easy sure. I suspect that it might not be simple, but we can give it a try.

100% for nss.

**Comment by stikonas** [comment]
Adding #306 to blockers.

**Comment by fosslinux** [comment]
I have (tentatively) created a 1.0 branch. Happy for almost anything to be merged into there at the moment, except for any large architectural changes.
